Sprint 2. Сервис сокращения URL
andranikuz/shortener pull request #12
Opened 2024-03-30 17:25 UTC by andranikuz

2024-04-01 06:29 UTC, rktkov requested changes

2024-04-01 06:29 UTC, rktkov commented on internal/storage/file/main.go
> +package file
Стоит переименовать файл.  main - файл, точка старта программы, а тут у нас ничего не стартует.

2024-04-01 06:29 UTC, rktkov commented on internal/storage/main.go
> +type DBInterface interface {
Определение интерфейса надо перенести в место использования.

2024-04-01 06:29 UTC, rktkov commented on internal/storage/main.go
> +func Get(id string) (*models.URL, error) {
Взаимодействовать с экземпляром лучше напрямую, а не через пакетные методы. Сам экземпляр стоит инициализировать в месте использования.

2024-04-01 06:29 UTC, rktkov commented on internal/app/app.go
> +	if err := storage.Init(); err != nil {
В структуру app стоит добавить поле DBInterface и тут его инициализировать.
И в этот же файл перенести определение интерфейса.

2024-04-01 14:44 UTC, andranikuz commented on internal/storage/file/main.go
> +package file
done

2024-04-01 14:44 UTC, andranikuz commented on internal/storage/main.go
> +type DBInterface interface {
done

2024-04-01 14:44 UTC, andranikuz commented on internal/storage/main.go
> +func Get(id string) (*models.URL, error) {
done

2024-04-01 14:46 UTC, andranikuz commented on internal/app/app.go
> +	if err := storage.Init(); err != nil {
Добавил в структуру. Но пришлось сделать публичную переменную, чтобы можно было получить DB в usecaces
Также, чтобы избежать цикличного импорта, перенес Router в пакет api (роутер импортит юзкейсы, а они app для получения DB)

2024-04-04 14:01 UTC, rktkov approved these changes

2024-04-04 14:41 UTC, merged