Sprint 7. Сервис сокращения URL
andranikuz/shortener pull request #24
Opened 2024-06-27 09:55 UTC by andranikuz

2024-06-28 16:30 UTC, far4599 requested changes
Требуется поправить ошибку с использованием фиксированного контекста в хендлерах

2024-06-28 16:30 UTC, far4599 commented on internal/api/rest/ping.go
>  func (h HTTPHandler) PingHandler(res http.ResponseWriter) {
это довольно плохой подход смешивать функционал разных уровней/слоев приложения в одном месте. хорошим решением является передача уже готового к использованию объекта и сохранение его в структуре HTTPHandler. чтобы из любого метода хендлеров ты мог дернуть нужный метод, а не инициализировать новое соединение с базой. 
представь, что кто-то создаст нагрузку в 100 запросов в секунду на ручку /ping и у тебя кончатся коннекты к базе на бесполезные пинги, а основной функционал приложения перестанет работать. 
кроме того инициализированные соединения с базой представляют собой паттерн прокси, под ковром прячется как протокол общения с базой, так и управление сетевыми соединениями. обычно драйверы реализуют внутри работу с пуллом коннектов, которые переиспользуются много раз, вместо того, чтобы каждый раз создавать новое соединение

2024-06-28 16:30 UTC, far4599 commented on internal/api/rest/ping.go
>  func (h HTTPHandler) PingHandler(res http.ResponseWriter) {
еще было бы здорово не использовать синглтон для конфига. лучшим решением является проброс объекта конфига из одного пакете и сохранение его в тот же HTTPHandler для последующего переиспользования. но самым лучшим решением является создание структуры конфига в том пакете, где он реально используется. а собирать и наполнять эти конфиги из разных пакетов можно в main.go

2024-06-28 16:30 UTC, far4599 commented on internal/app/application.go
>  	ctx context.Context
никогда не храни контекст в структурах

2024-06-28 16:30 UTC, far4599 commented on internal/app/application.go
>  	ctx context.Context
контекст - это очень временная штука. если ты его где-то сохраняешь - у тебя проблемы с кодом

2024-06-28 16:30 UTC, far4599 commented on internal/config/config.go
>  var Config AppConfig
глобальные переменные или синглтоны - это плохой подход к организации кода. они являются значимым ограничением для многопоточного тестирования и несут в себе риск вызвать race condition

2024-06-28 16:30 UTC, far4599 commented on internal/storage/storage.go
>  type Storage interface {
старайся избегать глобально доступных интерфейсов. через них ты создаешь ненужную связь пакетов в общим хранилищем в котором лежат такие интерфейсы. лучше использовать локальные неэкспортируемые интерфейсы только с теми методами, которые тебе нужны в пакете, в каждом пакете. кажется, что это противоречит DRY, но на самом деле это сильно экономит твое время по поддержке и тестированию этой истории

2024-06-28 16:30 UTC, far4599 commented on internal/container/container.go
>  	storage   storage.Storage
вот тут хорошо было бы использовать локальный интерфейс

2024-06-28 16:30 UTC, far4599 commented on internal/container/container.go
>  	shortener *shortener.Shortener
и для этой штуки тоже, не привязываться к конкретному типу в пакете shortener, а описать его поведение в небольшой локальном интерфейсе. и указать в нем не все метода, а только те, что реально используются в этом пакете

2024-06-28 16:30 UTC, far4599 commented on internal/container/container.go
>  func (c Container) Storage() (storage.Storage, error) {
а должны ли быть эти методы билдеры экспортруемыми?

2024-06-28 16:30 UTC, far4599 commented on internal/container/container.go
>  func (c Container) Storage() (storage.Storage, error) {
вообще, создавать и инициализировать объекты лучше в функции main - для нее не считается покрытие)  а если серьезно, то не нужно в одном пакете инициализировать его зависимости. каждая структура должна получать уже готовые и инициализированные зависимости. 
это позволит тебе выйти из приложения в случае ошибки коннекта к базе из-за неправильной конфигурации прямо в main еще до запуска сервера и всего такого

2024-06-28 16:30 UTC, far4599 commented on internal/services/shortener/get_full_url.go
>  func (s *Shortener) GetFullURL(ctx context.Context, id string) (string, error) {
не знаю, было ли это в задании. но в случае, когда ты что-то удалил, но хранишь это в базе, лучше возвращать безликую 404 ошибку - Not Found. А то мало ли пользователи забеспокоятся, почему это ты не возвращаешь им результат)) а говоришь, как будто бы он удален

2024-06-28 16:30 UTC, far4599 commented on internal/services/shortener/get_user_urls.go
>  func (s *Shortener) GetUserURLs(ctx context.Context, userID string) ([]models.URL, error) {
а что в этой ручке происходит в удаленными url?

2024-06-28 16:30 UTC, far4599 commented on internal/container/container.go
>  func (c Container) Storage() (storage.Storage, error) {
у этого есть еще один большой плюс, который в маленьком приложении не виден. Часто бывает, что от одной зависимости зависит очень много пакетов. Например, от инициализированного соединения с базой может зависит куча репозиториев. Создаешь зависимость в одном месте, передаешь ее через аргументы методов конструкторов во всех структуры/пакеты, которые от нее зависят. только так правильно работает dependency injection в go

2024-06-28 16:30 UTC, far4599 commented on tests/example_test.go
> +func ExampleHTTPHandler_GenerateShortURLHandler() {
почему бы не усилить пример и не сделать его с сигнатурой теста? тогда его можно будет запустить из IDE одним кликом, не придется ничего копировать/компилировать

2024-06-30 08:18 UTC, andranikuz commented on internal/services/shortener/get_full_url.go
>  func (s *Shortener) GetFullURL(ctx context.Context, id string) (string, error) {
Это требование было в задании - в случае удаления возвращаю 410

2024-06-30 08:19 UTC, andranikuz commented on internal/services/shortener/get_user_urls.go
>  func (s *Shortener) GetUserURLs(ctx context.Context, userID string) ([]models.URL, error) {
Возвращаются и удаленные. Кажется, на это настроены автотесты

2024-06-30 08:26 UTC, andranikuz commented on internal/api/rest/get_full_url.go
>  func (h HTTPHandler) GetFullURLHandler(ctx context.Context, res http.ResponseWriter, req *http.Request) {
Исправил

2024-06-30 08:26 UTC, andranikuz commented on internal/api/rest/ping.go
>  func (h HTTPHandler) PingHandler(res http.ResponseWriter) {
Исправил, использую единственный коннект

2024-06-30 08:27 UTC, andranikuz commented on internal/app/application.go
>  	ctx context.Context
Исправил

2024-07-02 14:03 UTC, far4599 requested changes
проблема с контекстом в хендлерах пока не решена

2024-07-02 14:03 UTC, far4599 commented on internal/api/rest/ping.go
> +	switch v := h.storage.(type) {
это слишком сложно. опять импортируешь тип данных из другого пакета - это плохо. чтобы не усложнять. тебе стоит просто добавить метод Ping в интерфейс storage.Storage и в структуру, которая этот интерфейс реализует. тогда ты сможешь вызывать его без всяких кастований и доступа к внутренним полям структур из других пакетов

2024-07-02 14:03 UTC, far4599 commented on tests/example_test.go
> +func ExampleHTTPHandler_GenerateShortURLHandler() {
так, вижу, что этот коммент не актуален. похоже, что IDE умеют запускать примеры

2024-07-03 17:24 UTC, andranikuz commented on internal/api/rest/delete_urls.go
> +	ctx := context.Background()
использую контекст request

2024-07-03 17:24 UTC, andranikuz commented on internal/api/rest/ping.go
> +	switch v := h.storage.(type) {
добавил метод в интерфейс

2024-07-03 18:39 UTC, far4599 approved these changes
по возможности стоит использовать указатели и вернуть контекст в методу удаления ссылок

2024-07-03 18:39 UTC, far4599 commented on internal/api/rest/generate_short_url.go
> +	shortURL, err := h.shortener.GenerateShortURL(req.Context(), fullURL, userID)
вот молодец!

2024-07-03 18:39 UTC, far4599 commented on internal/api/rest/delete_urls.go
> +	h.shortener.DeleteURLs(request, userID)
лучше не убирать контекст из методов других слоев. это нужно для того, чтобы потом когда-то их использовать. так работает пропагация контекста. хорошее правило: во всех функциях и методах, кроме чистых, передавать контекст первым аргументом.

2024-07-03 18:39 UTC, far4599 commented on internal/services/shortener/delete_urls.go
> +	go s.storage.DeleteURLs(context.Background(), ids, userID)
вот тут не очень понятно, зачем так сделал?

2024-07-03 18:39 UTC, far4599 commented on internal/services/shortener/get_full_url.go
> +func (s Shortener) GetFullURL(ctx context.Context, id string) (string, error) {
вот тут тоже не очень понятно, зачем это изменение. когда ресивер является указателем, то методы работают с исходной структурой. в твоем случае это приводит к копированию. с точки зрения производительности это не особо существенно, но это может стать препятствием для передачи объекта в то место, где ожидается интерфейс. интерфейсы всегда требуют передачи объекта через указатель, а если у тебя ресиверы в методах не являются указателями, то это может привести к ошибке.

2024-07-03 18:39 UTC, far4599 commented on internal/services/shortener/shortener.go
> +func NewShortener(storage storage.Storage) Shortener {
а вот из конструктора всегда нужно возвращать указатель, потому что потом при передаче объекта не через указатель у тебя будет происходить копирование всего объекта. в твоем случае это не критично, так как в струтуре лежит одно интерфейсное поле - которое по сути указатель на объект и при копировании этот указатель просто копируется. но если бы у тебя была более сложная структура, например, с мьютексами, то в каждой копии была бы своя локальная копия мьютекса. 
в общем, стоит везде по возможности пользоваться указателями, это упрощает жизнь - ты всегда будешь работать с одним объектом, на который они все указывают. это и ресурсы экономит на копирование и всякие сайд эффекты ловить не будешь с локальными копиями полей.

2024-07-03 18:39 UTC, far4599 commented on internal/storage/storage.go
> +	Ping() error
отлично!

2024-07-03 18:46 UTC, far4599 commented on internal/services/shortener/delete_urls.go
> +	go s.storage.DeleteURLs(context.Background(), ids, userID)
аа, кажется я понял. у тебя метод запускается в горутине и контекст может быть уже отменен в момент ее выполнения. тут может быть 2 варианта:
1. очистить контекст от признака терминаци с помощью функции context.WithoutCancel и дальше на него уже не будет влиять отмена, пришедшая по стеку выше. при этом содержимое контекста останется прежним. Но на всякий случай нужно добавить в него новую логику терминации через context.WithTimeout, например. оставлять незавершенный контекст - плохая практика и верный способ приводящий к утечкам памяти. 
2. Не использовать горутину, а делать блокирующий вызов

2024-07-11 14:26 UTC, merged